### ISSUE TITLE
How to get the chatid?

### ISSUE THREAD

**Issue by xiangyingchang** [zhuorantan/TelegramGPT#1]
Hello, when I was getting the chatid, the browser returned the content as shown in the screenshot, and I didn't find the chatid. I don't understand the code, I wonder if you could help guide me?
![image](https://github.com/zhuorantan/TelegramGPT/assets/10992221/2079c353-bbff-4966-8c24-763f3d522413)

**Comment by zhuorantan** [comment]
If you are already running TelegramGPT, messages probably won't show up in the result of the endpoint, since they would be consumed by TelegramGPT. You can also find the chatID in the log of TelegramGPT after you send a message to the bot. There're also many tutorials out there with other approaches of getting the chatID. You can search for keywords "telegram bot get chat id".

**Comment by xiangyingchang** [comment]
> telegram bot get chat id

Thank you very much, I have already sorted it out and attached the link: https://stackoverflow.com/questions/32423837/telegram-bot-how-to-get-a-group-chat-id
